services:
    postgres:
        image: postgres:16
        container_name: postgres_container
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - commerce-network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        ports:
            - '5050:80'
        depends_on:
            - postgres
        networks:
            - commerce-network

    nest-app:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: nest_app_container
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        env_file:
            - .env
        networks:
            - commerce-network
        command: npm run start:dev

volumes:
    postgres_data:


networks:
    commerce-network:
